from pathlib import Path
import json,re,html
ROOT=Path(r'C:\Users\hz-user\Desktop\全自动')
OUT=ROOT/'generated_html_full'/'Atomfair_pipetting_HTML'
OUT.mkdir(parents=True,exist_ok=True)
HEADERS=["来源","商品中文名称","型号","产品名称（英文）","URL","简介","产品详情","代码","网站分类","主图","详情图","图片文件名","alt text","title","Caption","价格","💲","是否上传"]
def esc(x): return html.escape(str(x),quote=True)
def slug(s): return re.sub(r'[^A-Za-z0-9]+','_',s).strip('_')[:90] or 'item'
def dt(headers,rows):
    th=''.join(f'<th style="background:#111;color:#fff;border:1px solid #111;padding:11px 12px;text-align:left;">{esc(h)}</th>' for h in headers)
    trs=[]
    for r in rows:
        tds=[]
        for i,c in enumerate(r):
            wt='font-weight:700;' if i==0 else ''
            tds.append(f'<td style="border:1px solid #d7d7d7;padding:10px 12px;{wt}vertical-align:top;">{esc(c)}</td>')
        trs.append('<tr>'+''.join(tds)+'</tr>')
    return f'<table style="border-collapse:collapse;border:1px solid #111;font-size:14px;" border="0" width="100%" cellspacing="0" cellpadding="0"><thead><tr>{th}</tr></thead><tbody>{"".join(trs)}</tbody></table>'
def sec(t,b): return f'<table style="margin-bottom:34px;" border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td style="border-left:5px solid #111;padding-left:15px;padding-bottom:12px;"><h2 style="margin:0;font-size:18px;color:#111;text-transform:uppercase;font-weight:800;">{esc(t)}</h2></td></tr><tr><td style="padding-top:18px;">{b}</td></tr></tbody></table>'
def page(title,model,ptype,overview,features,specs,ordering,accessories=None):
    p=[f'<!-- Atomfair Complete Product HTML - Full-English Release --><div style="width:100%;background:#ffffff;padding:0;" align="center"><table style="width:100%;font-family:Arial,Helvetica,sans-serif;color:#333;line-height:1.58;background:#fff;" border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td style="padding:38px 20px;border-bottom:4px solid #111;"><h1 style="margin:0;font-size:26px;color:#111;font-weight:800;text-transform:uppercase;">{esc(title)}</h1><div style="margin-top:8px;font-size:14px;color:#333;">Product Type: {esc(ptype)}</div><div class="model" style="margin-top:10px;font-size:15px;color:#333;font-weight:700;">Atomfair Model: {esc(model)}</div><div style="margin-top:15px;display:inline-block;background:#111;color:#fff;padding:6px 15px;font-size:13px;font-weight:bold;letter-spacing:.6px;text-transform:uppercase;">Research-grade liquid handling platform</div></td></tr><tr><td style="padding:38px 20px;">']
    p.append(sec('Product Overview',''.join(f'<p style="margin:0 0 14px 0;font-size:15px;color:#444;text-align:justify;">{esc(x)}</p>' for x in overview)))
    p.append(sec('Key Features and Advantages','<ul style="margin:0;padding-left:22px;font-size:14px;color:#444;line-height:1.85;">'+''.join(f'<li style="margin-bottom:9px;">{esc(x)}</li>' for x in features)+'</ul>'))
    p.append(sec('Technical Specifications',dt(['Parameter','Specification / Available Values'],specs)))
    if accessories: p.append(sec('Included and Compatible Accessories',dt(['Accessory / Module','Reference Code','Specification','Compatibility / Use'],accessories)))
    p.append(sec('Atomfair Product Ordering and Configuration Table',dt(ordering[0],ordering[1])))
    p.append('<table style="background:#f7f7f7;border:1px solid #e0e0e0;margin-bottom:34px;" border="0" width="100%" cellspacing="0" cellpadding="22"><tbody><tr><td style="font-size:14px;color:#333;"><div style="margin-bottom:10px;"><strong>Data Handling Standard:</strong> HTML content is English only. Volume ranges, increments, test volumes, systematic errors, random errors, channel counts, sterilization suitability and accessory compatibility are preserved in structured tables.</div><div><strong>Ordering Standard:</strong> Each pipette, dispenser, controller, stand, tip, nozzle, holder or accessory receives a unique Atomfair order model.</div></td></tr></tbody></table></td></tr><tr><td style="padding:25px 20px;background:#111;text-align:center;"><div style="color:#fff;font-size:20px;font-weight:bold;margin-bottom:8px;letter-spacing:1px;">TAILORED SOLUTIONS FOR RESEARCH</div><div style="color:#ddd;font-size:13px;margin-bottom:18px;">For bulk orders, OEM requirements, accessory matching, platform selection or configuration confirmation, contact our engineering sales team.</div><div style="display:inline-block;background:#fff;color:#111;padding:12px 35px;font-weight:800;font-size:13px;text-transform:uppercase;letter-spacing:1px;border-radius:2px;">EMAIL: inquiry@atomfair.com</div></td></tr><tr><td style="padding:28px 20px;text-align:center;font-size:12px;color:#888;letter-spacing:1px;"><div style="margin-bottom:5px;text-transform:uppercase;"><strong>Supplier:</strong> Atomfair</div><div style="text-transform:uppercase;"><strong>Brand:</strong> ATOMFAIR&reg;</div></td></tr></tbody></table></div>')
    return ''.join(p)
def rec(cn,model,en,intro,code,cat):
    r={h:'' for h in HEADERS}; r.update({'来源':'','商品中文名称':cn,'型号':model,'产品名称（英文）':en,'简介':intro,'代码':code,'网站分类':cat}); return r
records=[]
manual_rows=[('0.1-2.5 uL','0.002 uL','2.5 / 1.25 / 0.25 uL','Systematic: +/-0.04 uL +/-1.4%; +/-0.03 uL +/-2.5%; +/-0.03 uL +/-12.0%','Random: +/-0.02 uL +/-0.7%; +/-0.02 uL +/-1.5%; +/-0.02 uL +/-6.0%'),('0.5-10 uL','0.01 uL','10 / 5 / 1 uL','Systematic: +/-0.10 uL +/-1.0%; +/-0.08 uL +/-1.5%; +/-0.03 uL +/-2.5%','Random: +/-0.04 uL +/-0.4%; +/-0.04 uL +/-0.8%; +/-0.02 uL +/-1.8%'),('2-20 uL','0.02 uL','20 / 10 / 2 uL','Systematic: +/-0.20 uL +/-1.0%; +/-0.12 uL +/-1.2%; +/-0.10 uL +/-5.0%','Random: +/-0.06 uL +/-0.3%; +/-0.06 uL +/-0.6%; +/-0.03 uL +/-1.5%'),('5-50 uL','0.05 uL','50 / 25 / 5 uL','Systematic: +/-0.45 uL +/-0.9%; +/-0.35 uL +/-1.4%; +/-0.15 uL +/-3.0%','Random: +/-0.15 uL +/-0.3%; +/-0.20 uL +/-0.8%; +/-0.08 uL +/-1.6%'),('10-100 uL','0.1 uL','100 / 50 / 10 uL','Systematic: +/-0.80 uL +/-0.8%; +/-0.50 uL +/-1.0%; +/-0.30 uL +/-3.0%','Random: +/-0.20 uL +/-0.2%; +/-0.15 uL +/-0.3%; +/-0.10 uL +/-1.0%'),('20-200 uL','0.2 uL','200 / 100 / 20 uL','Systematic: +/-1.20 uL +/-0.6%; +/-1.00 uL +/-1.0%; +/-0.50 uL +/-2.5%','Random: +/-0.40 uL +/-0.2%; +/-0.30 uL +/-0.3%; +/-0.14 uL +/-0.7%'),('30-300 uL','0.2 uL','300 / 150 / 30 uL','Systematic: +/-1.80 uL +/-0.6%; +/-1.50 uL +/-1.0%; +/-0.75 uL +/-2.5%','Random: +/-0.60 uL +/-0.2%; +/-0.45 uL +/-0.3%; +/-0.21 uL +/-0.7%'),('100-1000 uL','1 uL','1000 / 500 / 100 uL','Systematic: +/-6.00 uL +/-0.6%; +/-5.00 uL +/-1.0%; +/-3.00 uL +/-3.0%','Random: +/-2.00 uL +/-0.2%; +/-1.00 uL +/-0.2%; +/-0.60 uL +/-0.6%'),('500-5000 uL','5 uL','5000 / 2500 / 500 uL','Systematic: +/-30.00 uL +/-0.6%; +/-15.00 uL +/-0.6%; +/-12.00 uL +/-2.4%','Random: +/-10.00 uL +/-0.2%; +/-7.50 uL +/-0.3%; +/-3.00 uL +/-0.6%'),('1000-10000 uL','10 uL','10000 / 5000 / 1000 uL','Systematic: +/-60.00 uL +/-0.6%; +/-40.00 uL +/-0.8%; +/-30.00 uL +/-3.0%','Random: +/-20.00 uL +/-0.2%; +/-10.00 uL +/-0.2%; +/-6.00 uL +/-0.6%')]
multichannel_rows=[('8-channel adjustable','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','0.01 / 0.05 / 0.1 / 0.2 uL','Systematic and random error values retained by test volume in the source table.'),('12-channel adjustable','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','0.01 / 0.05 / 0.1 / 0.2 uL','Systematic and random error values retained by test volume in the source table.'),('16-channel adjustable','1-20 uL; 5-100 uL','0.01 / 0.1 uL','Systematic and random error values retained by test volume in the source table.')]
products=[
('Mi-Pette-LTS','AF-LH-MP-LTS','ATOMFAIR® Mi-Pette-LTS Manual Single-Channel Pipette','Manual pipette','0.1-1000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; high-temperature sterilization available',manual_rows),
('Mi-Pette','AF-LH-MP','ATOMFAIR® Mi-Pette Manual Pipette','Manual pipette','0.1-1000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; high-temperature sterilization available',manual_rows),
('HiPette-LTS','AF-LH-HP-LTS','ATOMFAIR® HiPette-LTS Full Autoclavable Manual Pipette','Manual pipette','0.1-1000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; high-temperature sterilization available',manual_rows),
('HiPette','AF-LH-HP','ATOMFAIR® HiPette Full Autoclavable Manual Pipette','Manual pipette','0.1-1000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; high-temperature sterilization available',manual_rows),
('MicroPette Plus','AF-LH-MICROPETTE-PLUS','ATOMFAIR® MicroPette Plus Full Autoclavable Manual Pipette','Manual pipette','0.1-20000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; high-temperature sterilization available',manual_rows+[('2000-20000 uL','100 uL','20000 / 10000 / 2000 uL','Systematic: +/-120 uL +/-0.60%; +/-120 uL +/-1.20%; +/-120 uL +/-6.00%','Random: +/-60 uL +/-0.30%; +/-60 uL +/-0.60%; +/-60 uL +/-3.00%')]),
('TopPette','AF-LH-TOPPETTE','ATOMFAIR® TopPette Manual Pipette','Manual pipette','0.1-20000 uL and 0.5-300 uL model families; single-channel adjustable; 8-channel and 12-channel adjustable options; partial high-temperature sterilization for lower half',manual_rows+[('2000-20000 uL','100 uL','20000 / 10000 / 2000 uL','Systematic: +/-120 uL +/-0.60%; +/-120 uL +/-1.20%; +/-120 uL +/-6.00%','Random: +/-60 uL +/-0.30%; +/-60 uL +/-0.60%; +/-60 uL +/-3.00%')]),
('MiniPette / Mini TopPette','AF-LH-MINI-PIPETTE','ATOMFAIR® MiniPette and Mini TopPette Fixed-Volume Mini Pipette','Manual mini pipette','Fixed-volume single-channel mini pipette; 25-300 uL and 5-300 uL ranges; not suitable for high-temperature sterilization',[('Fixed volumes','5, 10, 20, 25, 50, 100, 200, 250, 300 uL'),('Accuracy table','Fixed-volume systematic and random errors are preserved by nominal volume in the source table'),('Sterilization','Not autoclavable')]),
('E-Pette','AF-LH-E-PETTE','ATOMFAIR® E-Pette Electronic Pipette','Electronic pipette','0.5-2000 uL single-channel adjustable; lower half autoclavable',manual_rows[:8]),
('dPette+','AF-LH-DPETTE-PLUS','ATOMFAIR® dPette+ Electronic Pipette','Electronic pipette','0.5-1000 uL single-channel adjustable and 0.5-300 uL 8-channel adjustable; lower half autoclavable',manual_rows[:8]),
('dPette','AF-LH-DPETTE','ATOMFAIR® dPette Electronic Pipette','Electronic pipette','0.5-1000 uL single-channel adjustable; lower half autoclavable',manual_rows[:8]),
('dPette-S','AF-LH-DPETTE-S','ATOMFAIR® dPette-S Electronic Pipette','Electronic pipette','5-1000 uL single-channel adjustable; lower half autoclavable',manual_rows[3:8]),
('Levo Plus','AF-LH-LEVO-PLUS','ATOMFAIR® Levo Plus Motorized Pipette Filler','Motorized pipette filler','0.1-100 mL single-channel liquid handling controller; lower half or nozzle sterilization supported',[('Volume range','0.1-100 mL'),('Operation','Electric aspiration and dispensing'),('Sterilization','Adapter and nozzle sterilization supported'),('Applications','Serological pipettes and large-volume liquid transfer')]),
('Levo Me','AF-LH-LEVO-ME','ATOMFAIR® Levo Me Motorized Pipette Filler','Motorized pipette filler','0.1-100 mL single-channel liquid handling controller; lower half or nozzle sterilization supported',[('Volume range','0.1-100 mL'),('Operation','Electric aspiration and dispensing'),('Sterilization','Adapter and nozzle sterilization supported'),('Weight','About 200 g')]),
('Levo','AF-LH-LEVO','ATOMFAIR® Levo Manual Pipette Filler','Manual pipette filler','0.1-100 mL single-channel manual liquid transfer controller',[('Volume range','0.1-100 mL'),('Operation','Manual aspiration and dispensing'),('Compatibility','Serological pipettes')]),
('Levo E','AF-LH-LEVO-E','ATOMFAIR® Levo E Pipette Pump','Pipette pump','2-25 mL single-channel manual pipette pump; not autoclavable',[('Volume range','2-25 mL'),('Operation','Manual pump operation'),('Sterilization','Not autoclavable')]),
('StepMate','AF-LH-STEPMATE','ATOMFAIR® StepMate Repeating Pipette','Repeating pipette','0.5-50 mL single-channel repeating dispenser for aqueous solutions, high-viscosity liquids and volatile liquids',[('Volume range','0.5-50 mL'),('Operation','Manual repeating dispense'),('Compatibility','Dispenser tips'),('Applications','Serial dispensing and repetitive liquid transfer')]),
]
for src,model,en,ptype,intro,srows in products:
    spec=[('Source model',src),('Application','Aqueous solution pipetting unless otherwise specified'),('Operation mode',ptype),('Available volume range / notes',intro),('Calibration reference','User calibration follows ISO 8655-2 where indicated')]
    order=[]
    for idx,row in enumerate(srows,1):
        if len(row)==5:
            rng,inc,test,sys,rand=row; order.append([f'{model}-{idx:02d}',rng,inc,test,sys,rand])
        else:
            order.append([f'{model}-{idx:02d}',row[0],row[1] if len(row)>1 else '',row[2] if len(row)>2 else 'See source technical table','See source technical table','See source technical table'])
    code=page(en,model,ptype,[intro,'Product names follow the source manual while Atomfair assigns a unified order model. Volume ranges, increments, test volumes and error data are retained in structured tables.'],['Ergonomic liquid-handling design for routine laboratory use.','Volume range and channel configuration are separated for accurate ordering.','Accuracy and precision information is preserved by test volume wherever visible in the source table.','Compatible tips, stands, fillers or dispenser accessories are listed separately.'],spec,(['Unique Atomfair Order Model','Volume Range','Increment','Test Volume(s)','Systematic Error','Random Error'],order))
    (OUT/(slug(model)+'.html')).write_text(code,encoding='utf-8'); records.append(rec('移液器 '+src,model,en,intro,code,'Liquid Handling'))

# Multichannel pipettes must be independent ordering rows because each channel
# count and range family is a separate sellable specification.
multichannel_products=[
('Mi-Pette-LTS 8-channel','AF-LH-MP-LTS-8CH','ATOMFAIR® Mi-Pette-LTS 8-Channel Adjustable Pipette','8-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Autoclavable where source family indicates high-temperature sterilization'),
('Mi-Pette-LTS 12-channel','AF-LH-MP-LTS-12CH','ATOMFAIR® Mi-Pette-LTS 12-Channel Adjustable Pipette','12-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Autoclavable where source family indicates high-temperature sterilization'),
('Mi-Pette 8-channel','AF-LH-MP-8CH','ATOMFAIR® Mi-Pette 8-Channel Adjustable Pipette','8-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Autoclavable where source family indicates high-temperature sterilization'),
('Mi-Pette 12-channel','AF-LH-MP-12CH','ATOMFAIR® Mi-Pette 12-Channel Adjustable Pipette','12-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Autoclavable where source family indicates high-temperature sterilization'),
('HiPette-LTS 8-channel','AF-LH-HP-LTS-8CH','ATOMFAIR® HiPette-LTS 8-Channel Adjustable Pipette','8-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('HiPette-LTS 12-channel','AF-LH-HP-LTS-12CH','ATOMFAIR® HiPette-LTS 12-Channel Adjustable Pipette','12-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('HiPette-LTS 16-channel','AF-LH-HP-LTS-16CH','ATOMFAIR® HiPette-LTS 16-Channel Adjustable Pipette','16-channel full-autoclavable manual pipette','1-20 uL; 5-100 uL','Full high-temperature sterilization supported'),
('HiPette 8-channel','AF-LH-HP-8CH','ATOMFAIR® HiPette 8-Channel Adjustable Pipette','8-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('HiPette 12-channel','AF-LH-HP-12CH','ATOMFAIR® HiPette 12-Channel Adjustable Pipette','12-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('HiPette 16-channel','AF-LH-HP-16CH','ATOMFAIR® HiPette 16-Channel Adjustable Pipette','16-channel full-autoclavable manual pipette','1-20 uL; 5-100 uL','Full high-temperature sterilization supported'),
('MicroPette Plus 8-channel','AF-LH-MICROPETTE-PLUS-8CH','ATOMFAIR® MicroPette Plus 8-Channel Adjustable Pipette','8-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('MicroPette Plus 12-channel','AF-LH-MICROPETTE-PLUS-12CH','ATOMFAIR® MicroPette Plus 12-Channel Adjustable Pipette','12-channel full-autoclavable manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL','Full high-temperature sterilization supported'),
('TopPette 8-channel','AF-LH-TOPPETTE-8CH','ATOMFAIR® TopPette 8-Channel Adjustable Pipette','8-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL; 50-300 uL; 100-1000 uL','Lower half autoclavable where indicated'),
('TopPette 12-channel','AF-LH-TOPPETTE-12CH','ATOMFAIR® TopPette 12-Channel Adjustable Pipette','12-channel manual pipette','0.5-10 uL; 5-50 uL; 10-100 uL; 20-200 uL; 30-300 uL; 50-300 uL','Lower half autoclavable where indicated'),
('dPette+ 8-channel','AF-LH-DPETTE-PLUS-8CH','ATOMFAIR® dPette+ 8-Channel Electronic Pipette','8-channel electronic pipette','0.5-300 uL','Lower half autoclavable'),
]
for src,model,en,ptype,ranges,sterilization in multichannel_products:
    channel='16-channel' if '16-Channel' in en else ('12-channel' if '12-Channel' in en else '8-channel')
    srows=multichannel_rows if channel!='16-channel' else [multichannel_rows[2]]
    specs=[('Source model / specification',src),('Channel count',channel),('Available volume ranges',ranges),('Operation mode',ptype),('Sterilization suitability',sterilization),('Calibration reference','User calibration follows ISO 8655-2 where indicated')]
    order=[]
    for idx,row in enumerate(srows,1):
        if (channel=='16-channel' and '16-channel' in row[0]) or channel!='16-channel':
            order.append([f'{model}-{idx:02d}',row[0],row[1],row[2],row[3]])
    code=page(en,model,ptype,[f'{src} is listed as an independent multichannel pipette specification because channel count and volume range define separate orderable models.', 'The technical table preserves channel count, volume range, increments, and the source manual note that systematic and random error values are retained by test volume.'],['Separate Atomfair order model for the multichannel specification.','Volume range families are preserved for quotation and selection.','Suitable for microplate, PCR plate, ELISA, reagent transfer, and parallel liquid handling workflows.','Compatible tip selection must follow the channel count and volume range.'],specs,(['Unique Atomfair Order Model','Channel / Range Group','Volume Range','Increment','Accuracy / Precision Source'],order))
    (OUT/(slug(model)+'.html')).write_text(code,encoding='utf-8')
    records.append(rec('多道移液器 '+src,model,en,f'{src}: {channel}, ranges {ranges}.',code,'Liquid Handling'))
# Dispensers and vacuum products
others=[('DispensMate-HF','AF-LH-DM-HF','ATOMFAIR® DispensMate-HF Bottle-Top Dispenser','Hydrofluoric acid transfer and dispensing','1-10 mL','Manual','Autoclavable: yes'),('DispensMate','AF-LH-DM','ATOMFAIR® DispensMate Bottle-Top Dispenser','Reagent transfer and dispensing','0.5-60 mL','Manual','Autoclavable: no'),('DispensMate-Pro','AF-LH-DM-PRO','ATOMFAIR® DispensMate-Pro Bottle-Top Dispenser','Reagent transfer and dispensing','0.5-100 mL','Manual','Autoclavable: yes'),('dFlow','AF-LH-DFLOW','ATOMFAIR® dFlow Electronic Bottle-Top Dispenser','Reagent transfer and dispensing','0.1-99.90 mL','Electronic','Autoclavable: yes'),('dFlow-Pro','AF-LH-DFLOW-PRO','ATOMFAIR® dFlow-Pro Electronic Bottle-Top Dispenser','Reagent transfer and dispensing','0.1-99.999 mL','Electronic','Autoclavable: yes'),('dTitre','AF-LH-DTITRE','ATOMFAIR® dTitre Electronic Titrator','Titration operation for chemical analysis, food industry and environmental analysis','0.01-99.99 mL','Electronic','Autoclavable: yes'),('dTitre-Pro','AF-LH-DTITRE-PRO','ATOMFAIR® dTitre-Pro Electronic Titrator','Titration operation for chemical analysis, food industry and environmental analysis','0.010-99.999 mL','Electronic','Autoclavable: yes'),('dTitre-S','AF-LH-DTITRE-S','ATOMFAIR® dTitre-S Electronic Titrator','Titration operation for chemical analysis, food industry and environmental analysis','0.010-99.999 mL','Electronic','Autoclavable: yes'),('SafeVac','AF-LH-SAFEVAC','ATOMFAIR® SafeVac Vacuum Aspiration System','Liquid collection and disposal for cell culture fluids, suspensions and supernatants','Vacuum 0-600 mbar; collection bottle 4 L','Electronic','Autoclavable: no'),('EcoVac','AF-LH-ECOVAC','ATOMFAIR® EcoVac Economy Vacuum Aspiration System','Liquid collection and disposal for cell culture fluids, suspensions and supernatants','Vacuum 0-500 mbar; collection bottle 2 L','Electronic','Autoclavable: no'),('SmartVAC','AF-LH-SMARTVAC','ATOMFAIR® SmartVAC Benchtop Vacuum Aspiration System','Liquid collection and disposal for cell culture fluids, suspensions and supernatants','Vacuum 600 mbar; collection bottle 1 L','Electronic','Autoclavable: no')]
for src,model,en,app,rng,op,auto in others:
    specs=[('Source model',src),('Application',app),('Operation mode',op),('Range / capacity',rng),('Sterilization / autoclavability',auto)]
    code=page(en,model,'Liquid Handling Instrument',[f'{src} is used for {app.lower()} with {rng}.'],['Dedicated product record with complete range/capacity information.','Operation mode and sterilization suitability are preserved from the product overview table.','Suitable for liquid transfer, dispensing, titration or aspiration workflows according to model type.'],specs,(['Unique Atomfair Order Model','Source Item / Component','Specification Value'],[[model,src,'; '.join(f'{k}: {v}' for k,v in specs)]]))
    (OUT/(slug(model)+'.html')).write_text(code,encoding='utf-8'); records.append(rec('移液产品 '+src,model,en,f'{src}: {app}; {rng}.',code,'Liquid Handling'))
# Accessories and kits from visible notes/tables
acc=[('Single-channel calibration kit 1','7030700000','0.5-10 uL, 10-100 uL, 100-1000 uL, pipette stand and pipette tips','Manual single-channel pipette calibration'),('Single-channel calibration kit 2','7030800000','2-20 uL, 20-200 uL, 100-1000 uL, pipette stand and pipette tips','Manual single-channel pipette calibration'),('Single-channel calibration kit 3','7030900000','100-1000 uL, 0.5-5 mL, 1-10 mL, pipette stand and pipette tips','Manual single-channel pipette calibration'),('Pipette stand','AF-REF-STAND','Stand for single or multiple manual pipettes','Manual pipette storage'),('Levo adapter / nozzle','AF-REF-LEVO-NOZZLE','Adapter and nozzle set for serological pipette controllers','Levo Plus / Levo Me'),('Dispenser tips','AF-REF-DISP-TIPS','Dispenser tips for 0.5-50 mL repeating dispensing','StepMate'),('Bottle-top dispenser adapter set','AF-REF-BTD-ADP','Adapter set for bottle-top dispensers','DispensMate / DispensMate-Pro / dFlow series'),('Aspiration hand operator','AF-REF-VAC-HAND','Hand operator for aspiration systems','SafeVac / EcoVac / SmartVAC'),('Single-channel pipette tips','AF-REF-TIPS-SC','Tip family matched to 0.1 uL to 10 mL pipette ranges','Manual and electronic pipettes'),('Multichannel pipette tips','AF-REF-TIPS-MC','Tip family for 8-channel, 12-channel and 16-channel pipettes','Multichannel pipettes')]
for i,(name,ref,spec,compat) in enumerate(acc,1):
    model=f'AF-LH-ACC-{i:03d}'; en=f'ATOMFAIR® {name}'; intro=f'{name} is a liquid handling accessory for {compat.lower()}.'
    specs=[('Accessory name',name),('Reference code',ref),('Specification',spec),('Compatibility / use',compat)]
    code=page(en,model,'Liquid Handling Accessory',[intro,'Accessories are listed separately so kits, tips, stands, adapters, nozzles and aspiration parts can be ordered without losing configuration information.'],['Unique Atomfair accessory model.','Reference code or functional description is retained.','Compatibility is listed for ordering and after-sales support.'],specs,(['Unique Atomfair Order Model','Reference Code','Source Item / Component','Specification Value'],[[model,ref,name,spec]]))
    (OUT/(slug(model)+'_'+slug(name)+'.html')).write_text(code,encoding='utf-8'); records.append(rec('移液配件 '+name,model,en,intro,code,'Liquid Handling Accessories'))
path=ROOT/'pipetting_records.json'
path.write_text(json.dumps([{'sheetName':'Pipetting Series','folder':str(OUT),'records':records}],ensure_ascii=False,indent=2),encoding='utf-8')
bad=sum(1 for r in records if re.search(r'[\u4e00-\u9fff]',r['代码']))
print('Pipetting Series records',len(records),'html_cjk_issues',bad)
