from pathlib import Path
import json, re
p=Path(r'C:\Users\hz-user\Desktop\全自动\product_collection_records.json')
payload=json.loads(p.read_text(encoding='utf-8'))
intro_map={
'AF-LH-DTITRE-PRO-10ML':["The dTitre-Pro 10 mL electronic titration and dispensing system is configured for laboratory titration, dispensing, aspiration, and controlled liquid-transfer workflows where the maximum single transfer volume is 10 mL.","The instrument supports program-based operation and preserves experiment records, making it suitable for repeated method execution and documentation in chemical analysis, food testing, water analysis, and related laboratory applications.","This 10 mL specification is separated as its own Atomfair order model because the working range, minimum transfer volume, speed range, and accuracy table differ from the 25 mL and 50 mL specifications."],
'AF-LH-DTITRE-PRO-25ML':["The dTitre-Pro 25 mL electronic titration and dispensing system is intended for controlled titration and liquid handling where a larger single transfer volume is required than the 10 mL configuration.","The product supports program control, wireless connectivity functions listed in the source manual, and structured experimental record handling for repeatable laboratory workflows.","This 25 mL version is kept as an independent Atomfair model so its 25 mL piston specification, working range, minimum 20 uL transfer value, and accuracy data remain traceable."],
'AF-LH-DTITRE-PRO-50ML':["The dTitre-Pro 50 mL electronic titration and dispensing system is the high-volume configuration in the dTitre-Pro family, used where the method requires up to 50 mL single-transfer capacity.","It is suitable for laboratories that need programmable titration or dispensing with clear record management and external configuration support as described in the source product material.","The 50 mL configuration is listed separately because its working range, speed range, and working-accuracy values are specification-dependent."],
'AF-LH-DTITRE-S-10ML':["The dTitre-S 10 mL electronic titrator is configured for routine titration workflows requiring controlled dispensing from a 10 mL specification.","It retains the same source-defined working range, ISO 8655 reference, and working-accuracy structure while presenting the product as an independent Atomfair ordering model.","This version is suitable for laboratory titration tasks where a compact 10 mL configuration is sufficient and where clear volume-specific selection is needed."],
'AF-LH-DTITRE-S-25ML':["The dTitre-S 25 mL electronic titrator provides a mid-volume titration configuration for repeated laboratory titration tasks.","The source-defined working range, working temperature, quality standard, and accuracy values are preserved in structured tables to avoid mixing this version with the 10 mL or 50 mL specifications.","It is listed independently for quotation, replacement selection, and method matching where 25 mL capacity is the appropriate operating format."],
'AF-LH-DTITRE-S-50ML':["The dTitre-S 50 mL electronic titrator is the larger-volume version in the dTitre-S family.","It is intended for electronic titration workflows that benefit from a 50 mL nominal configuration while keeping ISO 8655 and source accuracy details visible for selection.","The model is separated from the 10 mL and 25 mL versions because the single-transfer volume and working-accuracy values are not interchangeable."],
'AF-LH-DFLOW-PRO-10ML':["The dFlow-Pro 10 mL electronic bottle-top dispenser is designed for intelligent reagent transfer, dispensing, and repetitive liquid handling from compatible reagent bottles.","The product material describes multiple operation modes, including manual dispensing, timed dispensing, automatic dispensing, and custom dispensing workflows, which makes the system suitable for repeated dispensing tasks in laboratory sample preparation.","This 10 mL specification is listed as a separate Atomfair model because its working range, speed range, minimum transfer volume, and accuracy values are specific to the 10 mL configuration."],
'AF-LH-DFLOW-PRO-25ML':["The dFlow-Pro 25 mL electronic bottle-top dispenser is a mid-volume configuration for controlled reagent dispensing and transfer from bottle-top setups.","It supports programmable dispensing workflows and record-oriented operation as shown in the source material, while retaining the volume-specific technical data in the specification tables.","The 25 mL configuration is treated as an independent product row so users can distinguish it from the 10 mL and 50 mL versions during ordering."],
'AF-LH-DFLOW-PRO-50ML':["The dFlow-Pro 50 mL electronic bottle-top dispenser is the largest visible dFlow-Pro configuration in the provided material.","It is intended for higher-volume reagent dispensing, serial dispensing, and controlled liquid-transfer workflows where a 50 mL single maximum transfer volume is required.","Its working range, speed range, connectivity notes, memory, screen, and accuracy data are preserved in the HTML tables for complete specification review."],
'AF-LH-DTITRE-10ML':["The dTitre 10 mL electronic titrator is used for precise titration operations where electronic control helps reduce manual intervention and improve repeatability.","The source material positions the product for fields such as analytical chemistry, food industry, and water analysis, with a 10 mL maximum piston volume and a working range from 0.01 mL to 99.99 mL.","This model is kept as a separate 10 mL order row so its speed range, temperature range, ISO 8655 reference, and accuracy values remain clear."],
}
for group in payload:
    for r in group['records']:
        code=r.get('代码','')
        paras=intro_map.get(r.get('型号'))
        if not paras:
            if 'Accessories' in r.get('网站分类',''):
                paras=[f"{r['产品名称（英文）']} is a configuration accessory for electronic titration or dispensing systems.","It is listed independently so each holder, adapter, probe, printer, software module, or liquid-path accessory can be ordered, replaced, and checked for compatibility without relying on the main instrument record.","The function and reference information from the source material are retained in the specification table for traceable configuration and after-sales support."]
            else:
                continue
        repl=''.join(f'<p style="margin:0 0 14px 0;font-size:15px;color:#444;text-align:justify;">{x}</p>' for x in paras)
        code2=re.sub(r'(<h2 style="margin:0;font-size:18px;color:#111;text-transform:uppercase;font-weight:800;">Product Overview</h2></td></tr><tr><td style="padding-top:18px;">)(.*?)(</td></tr></tbody></table><table style="margin-bottom:34px;" border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td style="border-left:5px solid #111;padding-left:15px;padding-bottom:12px;"><h2 style="margin:0;font-size:18px;color:#111;text-transform:uppercase;font-weight:800;">Key Features and Advantages</h2>)', r'\1'+repl+r'\3', code, flags=re.S)
        r['代码']=code2
p.write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
print('updated',sum(len(g['records']) for g in payload))
