from pathlib import Path
import json
p=Path(r'C:\Users\hz-user\Desktop\全自动\product_collection_records.json')
payload=json.loads(p.read_text(encoding='utf-8'))
intro_map={
'AF-LH-DTITRE-PRO-10ML':'The dTitre-Pro 10 mL electronic titration and dispensing system is configured for laboratory titration, dispensing, aspiration, and controlled liquid-transfer workflows where the maximum single transfer volume is 10 mL. It supports program-based operation and experiment-record handling for repeated method execution in chemical analysis, food testing, water analysis, and related laboratory applications. This 10 mL specification is separated from the 25 mL and 50 mL versions because the working range, minimum transfer volume, speed range, and accuracy table are specification-dependent.',
'AF-LH-DTITRE-PRO-25ML':'The dTitre-Pro 25 mL electronic titration and dispensing system is intended for controlled titration and liquid handling where a larger single transfer volume is required than the 10 mL configuration. It supports program control, source-listed wireless connectivity functions, and structured experimental record handling. This 25 mL version is kept as an independent Atomfair model so its piston specification, working range, minimum 20 uL transfer value, and accuracy data remain traceable.',
'AF-LH-DTITRE-PRO-50ML':'The dTitre-Pro 50 mL electronic titration and dispensing system is the high-volume configuration in the dTitre-Pro family, used where methods require up to 50 mL single-transfer capacity. It is suitable for programmable titration or dispensing with record management and external configuration support as described in the source material. Its working range, speed range, and accuracy values are specification-dependent and are therefore listed separately.',
'AF-LH-DTITRE-S-10ML':'The dTitre-S 10 mL electronic titrator is configured for routine titration workflows requiring controlled dispensing from a 10 mL specification. It retains the source-defined working range, ISO 8655 reference, and working-accuracy structure while presenting the product as an independent Atomfair ordering model. This version is suitable where a compact 10 mL configuration is sufficient and clear volume-specific selection is needed.',
'AF-LH-DTITRE-S-25ML':'The dTitre-S 25 mL electronic titrator provides a mid-volume titration configuration for repeated laboratory titration tasks. The source-defined working range, working temperature, quality standard, and accuracy values are preserved in structured tables. It is listed independently for quotation, replacement selection, and method matching where 25 mL capacity is the appropriate operating format.',
'AF-LH-DTITRE-S-50ML':'The dTitre-S 50 mL electronic titrator is the larger-volume version in the dTitre-S family. It is intended for electronic titration workflows that benefit from a 50 mL nominal configuration while keeping ISO 8655 and source accuracy details visible for selection. The single-transfer volume and working-accuracy values are not interchangeable with the 10 mL or 25 mL versions.',
'AF-LH-DFLOW-PRO-10ML':'The dFlow-Pro 10 mL electronic bottle-top dispenser is designed for intelligent reagent transfer, dispensing, and repetitive liquid handling from compatible reagent bottles. The source material describes manual dispensing, timed dispensing, automatic dispensing, and custom dispensing workflows. This 10 mL specification is listed separately because its working range, speed range, minimum transfer volume, and accuracy values are specific to the 10 mL configuration.',
'AF-LH-DFLOW-PRO-25ML':'The dFlow-Pro 25 mL electronic bottle-top dispenser is a mid-volume configuration for controlled reagent dispensing and transfer from bottle-top setups. It supports programmable dispensing workflows and record-oriented operation as shown in the source material, while retaining volume-specific technical data in the specification tables. The 25 mL configuration is treated as an independent product row to distinguish it from the 10 mL and 50 mL versions.',
'AF-LH-DFLOW-PRO-50ML':'The dFlow-Pro 50 mL electronic bottle-top dispenser is the largest visible dFlow-Pro configuration in the provided material. It is intended for higher-volume reagent dispensing, serial dispensing, and controlled liquid-transfer workflows where a 50 mL single maximum transfer volume is required. Its working range, speed range, connectivity notes, memory, screen, and accuracy data are preserved for complete review.',
'AF-LH-DTITRE-10ML':'The dTitre 10 mL electronic titrator is used for precise titration operations where electronic control helps reduce manual intervention and improve repeatability. The source material positions the product for analytical chemistry, food industry, and water analysis, with a 10 mL maximum piston volume and a working range from 0.01 mL to 99.99 mL. Its speed range, temperature range, ISO 8655 reference, and accuracy values are retained in the specification table.',
}
changed=0
for group in payload:
    for r in group['records']:
        m=r.get('型号')
        if m in intro_map:
            r['简介']=intro_map[m]
            changed+=1
        elif 'Accessories' in r.get('网站分类',''):
            r['简介']=f"{r['产品名称（英文）']} is a configuration accessory for electronic titration or dispensing systems. It is listed independently so the holder, adapter, probe, printer, software module, or liquid-path accessory can be ordered, replaced, and checked for compatibility without relying only on the main instrument record. The function and reference information from the source material are retained for traceable configuration and after-sales support."
            changed+=1
p.write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
print('updated_intro',changed)
